# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# Add user /bin dir to path
export PATH=$PATH:/usr/local/sbin:~/bin:~/.local/bin

# Ignore case in tab completion
set completion-ignore-case on

# Set prompt text
PS1="\@-\w\$ "

# Source operating system specific bashrc
OPNAME=`uname`
if [ $OPNAME == "Darwin" ] && [ -f ~/.bashmac ]; then
    . ~/.bashmac
elif [ $OPNAME == "Linux" ] && [ -f ~/.bashlinux ]; then
    . ~/.bashlinux
fi

# Set language to UTF-8
export LANG="en_US.UTF-8"

# source BP vars
stat $HOME/xtuml/BP.info &> /dev/null
if [[ 0 == $? ]]; then
  source $HOME/xtuml/BP.info
fi

# source include files
if [ -d ~/.bash_include ]; then
    for f in ~/.bash_include/*; do
        . $f
    done
fi

# set JAVA home
export JAVA_HOME=`/usr/libexec/java_home`

# Add user /bin dir to path
export PATH=$PATH:~/Library/Python/3.7/bin


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/levi/Downloads/google-cloud-sdk/path.bash.inc' ]; then . '/Users/levi/Downloads/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/levi/Downloads/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/levi/Downloads/google-cloud-sdk/completion.bash.inc'; fi
